coslr: true
criterions:
  PerformanceLoss:
    def_file: ./loss/SoftmaxLoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
model_dir: ./logs/CIFAR10_Imb200_LT/models/resnet32_uniform
networks:
  classifier:
    def_file: ./models/TauNormClassifier.py
    optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
    params: {dataset: CIFAR10_LT, feat_dim: 64, log_dir: ./logs/CIFAR10_Imb200_LT/clslearn/lws_resnet32_uniform,
      num_classes: 10, stage1_weights: false}
  feat_model:
    def_file: ./models/ResNet32Feature.py
    fix: true
    optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
    params: {dataset: CIFAR10_LT, dropout: null, log_dir: ./logs/CIFAR10_Imb200_LT/clslearn/lws_resnet32_uniform,
      stage1_weights: false, use_fc: false, use_selfatt: false}
shuffle: true
training_opt:
  backbone: resnet32
  batch_size: 512
  dataset: CIFAR10_LT
  display_step: 10
  feature_dim: 64
  log_dir: ./logs/CIFAR10_Imb200_LT/clslearn/lws_resnet32_uniform
  log_root: ./logs/CIFAR10_Imb200_LT
  num_classes: 10
  num_epochs: 5
  num_workers: 12
  open_threshold: 0.1
  sampler: {def_file: ./data/ClassAwareSampler.py, num_samples_cls: 4, type: ClassAwareSampler}
  scheduler_params: {gamma: 0.1, step_size: 1}
  stage: lws_resnet32_uniform
  sub_dir: clslearn
  cifar_imb_ratio: 200
  rebalance: stage2_lws

